### PR TITLE
No implicit any

### LINKED ISSUE #1: Project doesn't support noImplicitAny
Hi, your definition file seems completely broken. When I include it in my project without even using it I get all these errors:

```
typings/main/definitions/sequelize/index.d.ts(825,15): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(832,13): error TS7006: Parameter 'value' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(832,20): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(833,12): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1037,19): error TS7006: Parameter 'date' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1038,15): error TS7006: Parameter 'date' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1088,11): error TS7006: Parameter 'hext' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1209,15): error TS7006: Parameter 'type' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1209,21): error TS7006: Parameter 'srid' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1229,3): error TS7010: 'construcor', which lacks return-type annotation, implicitly has an 'any' return type.
typings/main/definitions/sequelize/index.d.ts(1229,14): error TS7006: Parameter 'type' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1229,20): error TS7006: Parameter 'srid' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1230,3): error TS7010: 'construcor', which lacks return-type annotation, implicitly has an 'any' return type.
typings/main/definitions/sequelize/index.d.ts(1343,34): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1343,43): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1346,37): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1346,46): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1348,36): error TS7006: Parameter 'attributes' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1348,48): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1350,36): error TS7006: Parameter 'dataValues' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1350,48): error TS7006: Parameter 'fields' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1350,56): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1353,36): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1353,42): error TS7006: Parameter 'primaryKeys' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1373,39): error TS7006: Parameter 'hash' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1373,45): error TS7006: Parameter 'omitNull' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1373,55): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1374,25): error TS7006: Parameter 'SubClass' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1374,35): error TS7006: Parameter 'SuperClass' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1376,27): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1376,33): error TS7006: Parameter 'begin' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1391,15): error TS7006: Parameter 'fn' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1391,19): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1397,15): error TS7006: Parameter 'col' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1401,15): error TS7006: Parameter 'val' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1405,15): error TS7006: Parameter 'val' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1409,15): error TS7006: Parameter 'conditionsOrPath' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1409,33): error TS7006: Parameter 'value' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1413,15): error TS7006: Parameter 'attribute' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1413,26): error TS7006: Parameter 'comparator' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1413,38): error TS7006: Parameter 'logic' implicitly has an 'any' type.
typings/main/definitions/sequelize/index.d.ts(1418,34): error TS7006: Parameter 'obj' implicitly has an 'any' type.
```

### PR DESCRIPTION
**Pull request by louy**
Fixes #1

### CODE REVIEW

**Comment by RichardJECooke** [comment]
I just downloaded the typings and I get:

typings/modules/sequelize/index.d.ts(1483,34): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1483,43): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1486,37): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1486,46): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1488,36): error TS7006: Parameter 'attributes' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1488,48): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1490,36): error TS7006: Parameter 'dataValues' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1490,48): error TS7006: Parameter 'fields' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1490,56): error TS7006: Parameter 'Model' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1493,36): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1493,42): error TS7006: Parameter 'primaryKeys' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1513,39): error TS7006: Parameter 'hash' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1513,45): error TS7006: Parameter 'omitNull' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1513,55): error TS7006: Parameter 'options' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1514,25): error TS7006: Parameter 'SubClass' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1514,35): error TS7006: Parameter 'SuperClass' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1516,27): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1516,33): error TS7006: Parameter 'begin' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1531,15): error TS7006: Parameter 'fn' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1531,19): error TS7006: Parameter 'args' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1537,15): error TS7006: Parameter 'col' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1541,15): error TS7006: Parameter 'val' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1545,15): error TS7006: Parameter 'val' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1549,15): error TS7006: Parameter 'conditionsOrPath' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1549,33): error TS7006: Parameter 'value' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1553,15): error TS7006: Parameter 'attribute' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1553,26): error TS7006: Parameter 'comparator' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1553,38): error TS7006: Parameter 'logic' implicitly has an 'any' type.
typings/modules/sequelize/index.d.ts(1558,34): error TS7006: Parameter 'obj' implicitly has an 'any' type.

(I assume this is the npm version, not the dt version)

**Comment by louy** [comment]
Can you try again? I hadn't published this to the typings registry until now.
typings/registry#509

**Comment by RichardJECooke** [comment]
Thanks. Compiles without error now. 

Weirdly though I can't get autocomplete to work in Atom for this module.
This code should work, right?
```
const Sequelize = require('sequelize');
const connection : Sequelize.Connection = new Sequelize({.......})
```

**Comment by louy** [comment]
no problem.

that's weird. yep it should work just fine.

**Pull request merged**
